"""empty message

Revision ID: 17cd1132bb2e
Revises: 
Create Date: 2020-10-22 15:13:36.935107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cd1132bb2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('Venue', 'eeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('eeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
