"""empty message

Revision ID: 191e864d3bd0
Revises: f69d7e790158
Create Date: 2020-10-17 18:16:07.356508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191e864d3bd0'
down_revision = 'f69d7e790158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
