"""empty message

Revision ID: 4908d4518365
Revises: f3c5445e9efe
Create Date: 2020-10-19 14:26:24.676738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4908d4518365'
down_revision = 'f3c5445e9efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('eeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'eeking_description')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
